"""The Report center — assemble a shareable report from checkable sections.

Upgrades the single "Export report" action into a chooser: pick which sections to
include (model description, each study's config + result, run diagnostics, data
provenance, validation note) and generate an HTML report (always) plus, optionally,
the OpenMC deck + PDF via the existing :meth:`MainWindow.export_report`. The HTML
assembly is a pure function so it is unit-testable without a display.
"""

from __future__ import annotations

import html
from pathlib import Path

from PySide6.QtWidgets import (
    QCheckBox,
    QDialog,
    QFileDialog,
    QLabel,
    QPushButton,
    QVBoxLayout,
)

from .uikit import make_selectable


def build_report_html(title: str, sections: list[tuple[str, list[str]]]) -> str:
    """A self-contained HTML report from (heading, lines) sections. Pure + testable."""
    parts = [
        "<!doctype html><html><head><meta charset='utf-8'>",
        f"<title>{html.escape(title)}</title>",
        "<style>body{font-family:-apple-system,Segoe UI,sans-serif;margin:2em;color:#222;}"
        "h1{border-bottom:2px solid #4a90d9;padding-bottom:.2em;}"
        "h2{color:#4a90d9;margin-top:1.4em;}"
        ".mono{font-family:ui-monospace,monospace;white-space:pre-wrap;}"
        ".foot{color:#888;font-size:.85em;margin-top:2em;}</style></head><body>",
        f"<h1>{html.escape(title)}</h1>",
    ]
    for heading, lines in sections:
        parts.append(f"<h2>{html.escape(heading)}</h2>")
        parts.append("<div class='mono'>"
                     + "<br>".join(html.escape(ln) for ln in lines) + "</div>")
    parts.append("<div class='foot'>Generated by NBEAST · neutron-flux Monte Carlo</div>")
    parts.append("</body></html>")
    return "\n".join(parts)


class ReportCenterDialog(QDialog):
    def __init__(self, main_window, parent=None):
        super().__init__(parent)
        self.main = main_window
        self.setWindowTitle("Report center")
        self.resize(420, 380)
        layout = QVBoxLayout(self)
        layout.addWidget(QLabel("Assemble a report from the selected sections:"))

        self._checks: dict[str, QCheckBox] = {}
        for key, label in (
            ("model", "Model description (template, materials, parameters)"),
            ("studies", "Studies (each study's configuration + result)"),
            ("diagnostics", "Run diagnostics (uncertainties, convergence cautions)"),
            ("provenance", "Data provenance (library, seed, versions)"),
            ("validation", "Validation note"),
        ):
            check = QCheckBox(label)
            check.setChecked(True)
            self._checks[key] = check
            layout.addWidget(check)

        self.deck_check = QCheckBox("Also export the OpenMC deck + PDF (needs a finished run)")
        self.deck_check.setChecked(True)
        layout.addWidget(self.deck_check)
        layout.addStretch(1)

        self.status = QLabel("")
        make_selectable(self.status)
        self.status.setWordWrap(True)
        self.status.setStyleSheet("color:#666;")
        layout.addWidget(self.status)

        generate = QPushButton("Generate report…")
        generate.clicked.connect(self._generate)
        layout.addWidget(generate)

    # ---- section builders (read from the main window) -------------------------
    def _sections(self) -> list[tuple[str, list[str]]]:
        main = self.main
        out: list[tuple[str, list[str]]] = []
        if self._checks["model"].isChecked():
            out.append(("Model", self._model_lines()))
        if self._checks["studies"].isChecked():
            out.append(("Studies", self._study_lines()))
        if self._checks["diagnostics"].isChecked() and main.last_diagnostics is not None:
            out.append(("Diagnostics", list(main.last_diagnostics.summary_lines())))
        if self._checks["provenance"].isChecked():
            out.append(("Provenance", self._provenance_lines()))
        if self._checks["validation"].isChecked():
            out.append(("Validation", [
                "NBEAST builds and runs OpenMC models; the transport is OpenMC's.",
                "Criticality is anchored to Godiva, Jezebel, and LEU-COMP-THERM-001;",
                "see docs/validation.md for the full benchmark table and honest limits."]))
        return out

    def _model_lines(self) -> list[str]:
        main = self.main
        lines = [f"Template: {main._template}"]
        from nbeast.core import materials

        if main.spec is not None:
            for role in main.spec.material_roles:
                key = main._material_values[main._template][role.key]
                spec = materials.LIBRARY.get(key)
                lines.append(f"  {role.label}: {spec.label if spec else key}")
            for p in main.spec.parameters:
                lines.append(f"  {p.label} = {main._param_values[main._template][p.key]} {p.unit}".rstrip())
        return lines

    def _study_lines(self) -> list[str]:
        lines = []
        for config in self.main.studies.configs():
            result = self.main.studies.get_result(config.study_id)
            lines.append(f"{config.name} [{config.kind}]")
            if config.params:
                lines.append("  config: " + ", ".join(f"{k}={v}" for k, v in config.params.items()))
            lines.append(f"  result: {result.summary if result else 'not run'}")
        return lines or ["(no studies)"]

    def _provenance_lines(self) -> list[str]:
        main = self.main
        return [f"Cross sections: {main._cross_sections or '(bundled starter)'}",
                f"Seed: {main.seed_spin.value()}",
                f"Batches / particles: {main.batches_spin.value()} / {main.particles_spin.value()}"]

    def _generate(self) -> None:
        directory = QFileDialog.getExistingDirectory(self, "Report center — choose an output folder")
        if not directory:
            return
        out = Path(directory)
        title = f"NBEAST report — {self.main.project.name}"
        (out / "report.html").write_text(build_report_html(title, self._sections()))
        msg = f"Report written to {out / 'report.html'}"
        if self.deck_check.isChecked():
            try:
                if self.main.export_report(out) is not None:
                    msg += " (+ OpenMC deck + PDF)"
            except Exception as exc:  # noqa: BLE001
                msg += f" (deck/PDF skipped: {exc})"
        self.status.setText(msg)